source 'https://rubygems.org'

#gem 'webdrivers', '~> 5.0', require: false 
gem 'chromedriver-helper'
gem 'selenium-webdriver'
gem 'capybara'
gem 'rspec'
gem 'site_prism'
gem 'cucumber'
gem 'pry'

#quando for usar no projeto colocar:
#require 'webdrivers'

#ou especifico 
#require 'webdrivers/chromedriver'
#require 'webdrivers/geckodriver'
#require 'webdrivers/iedriver'
#require 'webdrivers/edgedriver'